### ISSUE TITLE
Deprecated selector in `blackboard/index.less`

### ISSUE THREAD

**Issue by amenski** [mathiasbynens/atom-blackboard#9]
In `blackboard/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host,
atom-text-editor .gutter,
:host .gutter` => `atom-text-editor,atom-text-editor,
atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor.is-focused .cursor,
:host.is-focused .cursor` => `atom-text-editor.is-focused .cursor,atom-text-editor.is-focused .cursor`

* `atom-text-editor.is-focused .selection .region,
:host.is-focused .selection .region` => `atom-text-editor.is-focused .selection .region,atom-text-editor.is-focused .selection .region`

* `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
:host.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,
:host.is-focused .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,atom-text-editor.is-focused .line.cursor-line`

* `.comment` => `.syntax--comment`

* `.constant` => `.syntax--constant`

* `.entity` => `.syntax--entity`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.string,
.meta.verbatim` => `.syntax--string,
.syntax--meta.syntax--verbatim`

* `.support` => `.syntax--support`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.string .constant.other.placeholder` => `.syntax--string .syntax--constant.syntax--other.syntax--placeholder`

* `.meta.function-call.py` => `.syntax--meta.syntax--function-call.py`

* `.meta.tag,
.meta.tag .entity` => `.syntax--meta.syntax--tag,
.syntax--meta.syntax--tag .syntax--entity`

* `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`

* `.keyword.type.variant` => `.syntax--keyword.syntax--type.syntax--variant`

* `.source.ocaml .keyword.operator.symbol` => `.syntax--source.syntax--ocaml .syntax--keyword.syntax--operator.syntax--symbol`

* `.source.ocaml .keyword.operator.symbol.infix` => `.syntax--source.syntax--ocaml .syntax--keyword.syntax--operator.syntax--symbol.syntax--infix`

* `.source.ocaml .keyword.operator.symbol.prefix` => `.syntax--source.syntax--ocaml .syntax--keyword.syntax--operator.syntax--symbol.syntax--prefix`

* `.source.ocaml .keyword.operator.symbol.infix.floating-point` => `.syntax--source.syntax--ocaml .syntax--keyword.syntax--operator.syntax--symbol.syntax--infix.syntax--floating-point`

* `.source.ocaml .keyword.operator.symbol.prefix.floating-point` => `.syntax--source.syntax--ocaml .syntax--keyword.syntax--operator.syntax--symbol.syntax--prefix.syntax--floating-point`

* `.source.ocaml .constant.numeric.floating-point` => `.syntax--source.syntax--ocaml .syntax--constant.syntax--numeric.syntax--floating-point`

* `.text.tex.latex .meta.function.environment` => `.syntax--text.syntax--tex.syntax--latex .syntax--meta.syntax--function.syntax--environment`

* `.text.tex.latex .meta.function.environment .meta.function.environment` => `.syntax--text.syntax--tex.syntax--latex .syntax--meta.syntax--function.syntax--environment .syntax--meta.syntax--function.syntax--environment`

* `.text.tex.latex .support.function` => `.syntax--text.syntax--tex.syntax--latex .syntax--support.syntax--function`

* `.source.plist .string.unquoted,
.source.plist .keyword.operator` => `.syntax--source.syntax--plist .syntax--string.syntax--unquoted,
.syntax--source.syntax--plist .syntax--keyword.syntax--operator`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mathiasbynens** [comment]
👍 Would you like to submit a pull request?

**Comment by viljamis** [comment]
@mathiasbynens I just submitted a pull request for this.
